// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/exam/presentation/subject_exams/cubit/subject_exams_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/exam/domain/entities/exam_entity.dart' as _i5;
import 'package:examy/feature/exam/domain/entities/exam_history_entity.dart'
    as _i8;
import 'package:examy/feature/exam/domain/use_cases/get_exam_history_by_subject_use_case.dart'
    as _i7;
import 'package:examy/feature/exam/domain/use_cases/get_exams_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetExamsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamsUseCase extends _i1.Mock implements _i2.GetExamsUseCase {
  MockGetExamsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.ExamEntity>>> call({
    String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#subjectId: subjectId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.ExamEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.ExamEntity>>>(
                    this,
                    Invocation.method(#call, [], {#subjectId: subjectId}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.ExamEntity>>>);
}

/// A class which mocks [GetExamHistoryBySubjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamHistoryBySubjectUseCase extends _i1.Mock
    implements _i7.GetExamHistoryBySubjectUseCase {
  MockGetExamHistoryBySubjectUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.ExamHistoryEntity>> call({required String? subjectId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#subjectId: subjectId}),
            returnValue: _i3.Future<List<_i8.ExamHistoryEntity>>.value(
              <_i8.ExamHistoryEntity>[],
            ),
          )
          as _i3.Future<List<_i8.ExamHistoryEntity>>);
}
