// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/forgot_password/data/data_sources/remote/forgot_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:examy/feature/forgot_password/api/client/forgot_password_api_client.dart'
    as _i3;
import 'package:examy/feature/forgot_password/data/models/forgot_password_request_model.dart'
    as _i5;
import 'package:examy/feature/forgot_password/data/models/message_response_model.dart'
    as _i2;
import 'package:examy/feature/forgot_password/data/models/reset_password_request_model.dart'
    as _i7;
import 'package:examy/feature/forgot_password/data/models/verify_reset_code_request_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageResponseModel_0 extends _i1.SmartFake
    implements _i2.MessageResponseModel {
  _FakeMessageResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgotPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordApiClient extends _i1.Mock
    implements _i3.ForgotPasswordApiClient {
  MockForgotPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MessageResponseModel> forgotPassword(
    _i5.ForgotPasswordRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i4.Future<_i2.MessageResponseModel>.value(
              _FakeMessageResponseModel_0(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageResponseModel>);

  @override
  _i4.Future<_i2.MessageResponseModel> verifyResetCode(
    _i6.VerifyResetCodeRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i4.Future<_i2.MessageResponseModel>.value(
              _FakeMessageResponseModel_0(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageResponseModel>);

  @override
  _i4.Future<_i2.MessageResponseModel> resetPassword(
    _i7.ResetPasswordRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i4.Future<_i2.MessageResponseModel>.value(
              _FakeMessageResponseModel_0(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageResponseModel>);
}
