// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/profile/presentation/view_model/profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:examy/core/base_response/base_response.dart' as _i5;
import 'package:examy/feature/profile/domain/entities/change_password_entity.dart'
    as _i11;
import 'package:examy/feature/profile/domain/entities/change_password_params.dart'
    as _i12;
import 'package:examy/feature/profile/domain/entities/profile_entity.dart'
    as _i6;
import 'package:examy/feature/profile/domain/entities/update_profile_params.dart'
    as _i9;
import 'package:examy/feature/profile/domain/repos/profile_repo.dart' as _i2;
import 'package:examy/feature/profile/domain/use_cases/change_passoword_use_case.dart'
    as _i10;
import 'package:examy/feature/profile/domain/use_cases/get_profile_use_case.dart'
    as _i3;
import 'package:examy/feature/profile/domain/use_cases/update_profile_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileRepo_0 extends _i1.SmartFake implements _i2.ProfileRepo {
  _FakeProfileRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i3.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.ProfileEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i8.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>> call({
    required _i9.UpdateProfileParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.ProfileEntity>>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ProfileEntity>>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i10.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileRepo get profileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#profileRepo),
            returnValue: _FakeProfileRepo_0(
              this,
              Invocation.getter(#profileRepo),
            ),
          )
          as _i2.ProfileRepo);

  @override
  _i4.Future<_i5.BaseResponse<_i11.ChangePasswordEntity>> call(
    _i12.ChangePasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i11.ChangePasswordEntity>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i11.ChangePasswordEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i11.ChangePasswordEntity>>);
}
