// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/profile/data/data_sources/remote/profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:examy/feature/profile/api/client/profile_api_client.dart'
    as _i4;
import 'package:examy/feature/profile/data/models/change_password_request_model.dart'
    as _i7;
import 'package:examy/feature/profile/data/models/change_password_response_model.dart'
    as _i3;
import 'package:examy/feature/profile/data/models/profile_response_model.dart'
    as _i2;
import 'package:examy/feature/profile/data/models/update_profile_request_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileResponseModel_0 extends _i1.SmartFake
    implements _i2.ProfileResponseModel {
  _FakeProfileResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseModel_1 extends _i1.SmartFake
    implements _i3.ChangePasswordResponseModel {
  _FakeChangePasswordResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiClient extends _i1.Mock implements _i4.ProfileApiClient {
  MockProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProfileResponseModel> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i2.ProfileResponseModel>.value(
              _FakeProfileResponseModel_0(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponseModel>);

  @override
  _i5.Future<_i2.ProfileResponseModel> updateProfile({
    required _i6.UpdateProfileRequestModel? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#body: body}),
            returnValue: _i5.Future<_i2.ProfileResponseModel>.value(
              _FakeProfileResponseModel_0(
                this,
                Invocation.method(#updateProfile, [], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i2.ProfileResponseModel>);

  @override
  _i5.Future<_i3.ChangePasswordResponseModel> changePassword({
    required _i7.ChangePasswordRequestModel? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {#body: body}),
            returnValue: _i5.Future<_i3.ChangePasswordResponseModel>.value(
              _FakeChangePasswordResponseModel_1(
                this,
                Invocation.method(#changePassword, [], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i3.ChangePasswordResponseModel>);
}
