// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/home/data/data_sources/remote/explore_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:examy/feature/home/api/client/explore_api_client.dart' as _i4;
import 'package:examy/feature/home/data/models/subject_details_response_model.dart'
    as _i3;
import 'package:examy/feature/home/data/models/subjects_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubjectsResponseModel_0 extends _i1.SmartFake
    implements _i2.SubjectsResponseModel {
  _FakeSubjectsResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubjectDetailsResponseModel_1 extends _i1.SmartFake
    implements _i3.SubjectDetailsResponseModel {
  _FakeSubjectDetailsResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExploreApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreApiClient extends _i1.Mock implements _i4.ExploreApiClient {
  MockExploreApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SubjectsResponseModel> getSubjects({int? page, int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<_i2.SubjectsResponseModel>.value(
              _FakeSubjectsResponseModel_0(
                this,
                Invocation.method(#getSubjects, [], {
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.SubjectsResponseModel>);

  @override
  _i5.Future<_i3.SubjectDetailsResponseModel> getSubjectDetails(
    String? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectDetails, [subjectId]),
            returnValue: _i5.Future<_i3.SubjectDetailsResponseModel>.value(
              _FakeSubjectDetailsResponseModel_1(
                this,
                Invocation.method(#getSubjectDetails, [subjectId]),
              ),
            ),
          )
          as _i5.Future<_i3.SubjectDetailsResponseModel>);
}
