// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/exam/domain/use_cases/check_questions_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/exam/domain/entities/check_result_entity.dart'
    as _i9;
import 'package:examy/feature/exam/domain/entities/exam_entity.dart' as _i7;
import 'package:examy/feature/exam/domain/entities/question_entity.dart' as _i8;
import 'package:examy/feature/exam/domain/entities/subject_entity.dart' as _i5;
import 'package:examy/feature/exam/domain/repos/exam_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExamRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamRepo extends _i1.Mock implements _i2.ExamRepo {
  MockExamRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.SubjectEntity>>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.SubjectEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.SubjectEntity>>>(
                    this,
                    Invocation.method(#getSubjects, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.SubjectEntity>>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i7.ExamEntity>>> getExams({
    String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExams, [], {#subjectId: subjectId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i7.ExamEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i7.ExamEntity>>>(
                    this,
                    Invocation.method(#getExams, [], {#subjectId: subjectId}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i7.ExamEntity>>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.ExamEntity>> getExamById({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamById, [], {#examId: examId}),
            returnValue: _i3.Future<_i4.BaseResponse<_i7.ExamEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i7.ExamEntity>>(
                this,
                Invocation.method(#getExamById, [], {#examId: examId}),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.ExamEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i8.QuestionEntity>>> getQuestionsByExam({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByExam, [], {#examId: examId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i8.QuestionEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i8.QuestionEntity>>>(
                    this,
                    Invocation.method(#getQuestionsByExam, [], {
                      #examId: examId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i8.QuestionEntity>>>);

  @override
  _i3.Future<_i4.BaseResponse<_i9.CheckResultEntity>> checkQuestions({
    required List<Map<String, String>>? answers,
    required int? time,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkQuestions, [], {
              #answers: answers,
              #time: time,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i9.CheckResultEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i9.CheckResultEntity>>(
                    this,
                    Invocation.method(#checkQuestions, [], {
                      #answers: answers,
                      #time: time,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i9.CheckResultEntity>>);
}
