// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/exam/domain/use_cases/get_exam_history_by_subject_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/feature/exam/domain/entities/exam_history_entity.dart'
    as _i4;
import 'package:examy/feature/exam/domain/repos/exam_history_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExamHistoryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamHistoryRepo extends _i1.Mock implements _i2.ExamHistoryRepo {
  MockExamHistoryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExamHistoryEntity>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i3.Future<List<_i4.ExamHistoryEntity>>.value(
              <_i4.ExamHistoryEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ExamHistoryEntity>>);

  @override
  _i3.Future<List<_i4.ExamHistoryEntity>> getHistoryBySubject({
    required String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoryBySubject, [], {
              #subjectId: subjectId,
            }),
            returnValue: _i3.Future<List<_i4.ExamHistoryEntity>>.value(
              <_i4.ExamHistoryEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ExamHistoryEntity>>);

  @override
  _i3.Future<void> saveHistoryEntry(_i4.ExamHistoryEntity? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveHistoryEntry, [entry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
