// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/forgot_password/domain/use_cases/forgot_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/forgot_password/domain/entities/forgot_password_entity.dart'
    as _i6;
import 'package:examy/feature/forgot_password/domain/entities/message_entity.dart'
    as _i5;
import 'package:examy/feature/forgot_password/domain/entities/reset_password_entity.dart'
    as _i9;
import 'package:examy/feature/forgot_password/domain/entities/verify_reset_code_entity.dart'
    as _i8;
import 'package:examy/feature/forgot_password/domain/repos/forgot_password_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgotPasswordRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordRepo extends _i1.Mock
    implements _i2.ForgotPasswordRepo {
  MockForgotPasswordRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.MessageEntity>> forgotPassword({
    required _i6.ForgotPasswordEntity? forgotPasswordEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {
              #forgotPasswordEntity: forgotPasswordEntity,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.MessageEntity>>(
                this,
                Invocation.method(#forgotPassword, [], {
                  #forgotPasswordEntity: forgotPasswordEntity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.MessageEntity>> verifyResetCode({
    required _i8.VerifyResetCodeEntity? verifyResetCodeEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeEntity: verifyResetCodeEntity,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.MessageEntity>>(
                this,
                Invocation.method(#verifyResetCode, [], {
                  #verifyResetCodeEntity: verifyResetCodeEntity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.MessageEntity>> resetPassword({
    required _i9.ResetPasswordEntity? resetPasswordEntity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordEntity: resetPasswordEntity,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.MessageEntity>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordEntity: resetPasswordEntity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.MessageEntity>>);
}
