// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/exam/data/data_sources/remote/exam_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;

import 'package:examy/feature/exam/api/client/exam_api_client.dart' as _i7;
import 'package:examy/feature/exam/data/models/check_questions_request_model.dart'
    as _i9;
import 'package:examy/feature/exam/data/models/check_questions_response_model.dart'
    as _i6;
import 'package:examy/feature/exam/data/models/exam_by_id_response_model.dart'
    as _i4;
import 'package:examy/feature/exam/data/models/exams_response_model.dart'
    as _i3;
import 'package:examy/feature/exam/data/models/questions_response_model.dart'
    as _i5;
import 'package:examy/feature/exam/data/models/subjects_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubjectsResponseModel_0 extends _i1.SmartFake
    implements _i2.SubjectsResponseModel {
  _FakeSubjectsResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExamsResponseModel_1 extends _i1.SmartFake
    implements _i3.ExamsResponseModel {
  _FakeExamsResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExamByIdResponseModel_2 extends _i1.SmartFake
    implements _i4.ExamByIdResponseModel {
  _FakeExamByIdResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuestionsResponseModel_3 extends _i1.SmartFake
    implements _i5.QuestionsResponseModel {
  _FakeQuestionsResponseModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCheckQuestionsResponseModel_4 extends _i1.SmartFake
    implements _i6.CheckQuestionsResponseModel {
  _FakeCheckQuestionsResponseModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExamApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamApiClient extends _i1.Mock implements _i7.ExamApiClient {
  MockExamApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SubjectsResponseModel> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i8.Future<_i2.SubjectsResponseModel>.value(
              _FakeSubjectsResponseModel_0(
                this,
                Invocation.method(#getSubjects, []),
              ),
            ),
          )
          as _i8.Future<_i2.SubjectsResponseModel>);

  @override
  _i8.Future<_i3.ExamsResponseModel> getExams({String? subject}) =>
      (super.noSuchMethod(
            Invocation.method(#getExams, [], {#subject: subject}),
            returnValue: _i8.Future<_i3.ExamsResponseModel>.value(
              _FakeExamsResponseModel_1(
                this,
                Invocation.method(#getExams, [], {#subject: subject}),
              ),
            ),
          )
          as _i8.Future<_i3.ExamsResponseModel>);

  @override
  _i8.Future<_i4.ExamByIdResponseModel> getExamById(String? examId) =>
      (super.noSuchMethod(
            Invocation.method(#getExamById, [examId]),
            returnValue: _i8.Future<_i4.ExamByIdResponseModel>.value(
              _FakeExamByIdResponseModel_2(
                this,
                Invocation.method(#getExamById, [examId]),
              ),
            ),
          )
          as _i8.Future<_i4.ExamByIdResponseModel>);

  @override
  _i8.Future<_i5.QuestionsResponseModel> getQuestionsByExam({
    required String? exam,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByExam, [], {#exam: exam}),
            returnValue: _i8.Future<_i5.QuestionsResponseModel>.value(
              _FakeQuestionsResponseModel_3(
                this,
                Invocation.method(#getQuestionsByExam, [], {#exam: exam}),
              ),
            ),
          )
          as _i8.Future<_i5.QuestionsResponseModel>);

  @override
  _i8.Future<_i6.CheckQuestionsResponseModel> checkQuestions(
    _i9.CheckQuestionsRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkQuestions, [request]),
            returnValue: _i8.Future<_i6.CheckQuestionsResponseModel>.value(
              _FakeCheckQuestionsResponseModel_4(
                this,
                Invocation.method(#checkQuestions, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.CheckQuestionsResponseModel>);
}
