// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/profile/data/repos/profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/core/storage/secure_storage_service.dart' as _i10;
import 'package:examy/feature/profile/data/data_sources/remote/profile_remote_data_source.dart'
    as _i2;
import 'package:examy/feature/profile/data/models/change_password_request_model.dart'
    as _i9;
import 'package:examy/feature/profile/data/models/change_password_response_model.dart'
    as _i8;
import 'package:examy/feature/profile/data/models/profile_response_model.dart'
    as _i5;
import 'package:examy/feature/profile/data/models/update_profile_request_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i2.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ProfileResponseModel>>(
                    this,
                    Invocation.method(#getProfile, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>> updateProfile({
    required _i7.UpdateProfileRequestModel? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#body: body}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ProfileResponseModel>>(
                    this,
                    Invocation.method(#updateProfile, [], {#body: body}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ChangePasswordResponseModel>> changePassword({
    required _i9.ChangePasswordRequestModel? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {#body: body}),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i8.ChangePasswordResponseModel>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i8.ChangePasswordResponseModel>
                  >(
                    this,
                    Invocation.method(#changePassword, [], {#body: body}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ChangePasswordResponseModel>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i10.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
