// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/profile/domain/use_cases/update_profile_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/profile/domain/entities/change_password_entity.dart'
    as _i8;
import 'package:examy/feature/profile/domain/entities/change_password_params.dart'
    as _i9;
import 'package:examy/feature/profile/domain/entities/profile_entity.dart'
    as _i5;
import 'package:examy/feature/profile/domain/entities/update_profile_params.dart'
    as _i7;
import 'package:examy/feature/profile/domain/repos/profile_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i2.ProfileRepo {
  MockProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.ProfileEntity>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>> updateProfile({
    required _i7.UpdateProfileParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#params: params}),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.ProfileEntity>>(
                this,
                Invocation.method(#updateProfile, [], {#params: params}),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ProfileEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ChangePasswordEntity>> changePassword(
    _i9.ChangePasswordParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [params]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.ChangePasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i8.ChangePasswordEntity>>(
                    this,
                    Invocation.method(#changePassword, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ChangePasswordEntity>>);
}
