// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/exam/data/repos/exam_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/exam/data/data_sources/remote/exam_remote_data_source.dart'
    as _i2;
import 'package:examy/feature/exam/data/models/check_questions_request_model.dart'
    as _i11;
import 'package:examy/feature/exam/data/models/check_questions_response_model.dart'
    as _i10;
import 'package:examy/feature/exam/data/models/exam_by_id_response_model.dart'
    as _i8;
import 'package:examy/feature/exam/data/models/exams_response_model.dart'
    as _i7;
import 'package:examy/feature/exam/data/models/questions_response_model.dart'
    as _i9;
import 'package:examy/feature/exam/data/models/subjects_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExamRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamRemoteDataSource extends _i1.Mock
    implements _i2.ExamRemoteDataSource {
  MockExamRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.SubjectsResponseModel>>(
                    this,
                    Invocation.method(#getSubjects, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.ExamsResponseModel>> getExams({
    String? subjectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExams, [], {#subjectId: subjectId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.ExamsResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.ExamsResponseModel>>(
                    this,
                    Invocation.method(#getExams, [], {#subjectId: subjectId}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.ExamsResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.ExamByIdResponseModel>> getExamById({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamById, [], {#examId: examId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.ExamByIdResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i8.ExamByIdResponseModel>>(
                    this,
                    Invocation.method(#getExamById, [], {#examId: examId}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ExamByIdResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i9.QuestionsResponseModel>> getQuestionsByExam({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByExam, [], {#examId: examId}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i9.QuestionsResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i9.QuestionsResponseModel>>(
                    this,
                    Invocation.method(#getQuestionsByExam, [], {
                      #examId: examId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i9.QuestionsResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i10.CheckQuestionsResponseModel>>
  checkQuestions({required _i11.CheckQuestionsRequestModel? request}) =>
      (super.noSuchMethod(
            Invocation.method(#checkQuestions, [], {#request: request}),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i10.CheckQuestionsResponseModel>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i10.CheckQuestionsResponseModel>
                  >(
                    this,
                    Invocation.method(#checkQuestions, [], {#request: request}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i10.CheckQuestionsResponseModel>>);
}
