// Mocks generated by Mockito 5.4.6 from annotations
// in examy/test/feature/home/data/repos/explore_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:examy/core/base_response/base_response.dart' as _i4;
import 'package:examy/feature/home/data/data_sources/remote/explore_remote_data_source.dart'
    as _i2;
import 'package:examy/feature/home/data/models/subject_details_response_model.dart'
    as _i7;
import 'package:examy/feature/home/data/models/subjects_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExploreRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreRemoteDataSource extends _i1.Mock
    implements _i2.ExploreRemoteDataSource {
  MockExploreRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>> getSubjects({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, [], {#page: page, #limit: limit}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.SubjectsResponseModel>>(
                    this,
                    Invocation.method(#getSubjects, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.SubjectsResponseModel>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.SubjectDetailsResponseModel>>
  getSubjectDetails(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectDetails, [subjectId]),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i7.SubjectDetailsResponseModel>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i7.SubjectDetailsResponseModel>
                  >(this, Invocation.method(#getSubjectDetails, [subjectId])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.SubjectDetailsResponseModel>>);
}
